[workspace]
members = [
    "kernel",
    "userland",
]
resolver = "2"

# Shared profile settings (must be at workspace root)
[profile.dev]
panic = "abort"
opt-level = 2
overflow-checks = true
debug = false

[profile.release]
panic = "abort"
lto = "fat"
opt-level = 3
codegen-units = 1
strip = false
overflow-checks = false
