[package]
name = "astral-kernel"
version = "0.3.0"
edition = "2021"
authors = ["Astral OS Team"]

[dependencies]
spin = { version = "0.9", default-features = false, features = ["spin_mutex"] }
limine = "0.5"
fontdue = { version = "0.9", default-features = false, features = ["hashbrown"] }
ahash = { version = "0.8.7", default-features = false }
hashbrown = { version = "0.14", default-features = false, features = ["ahash", "inline-more"] }
bitflags = "2.4"

[build-dependencies]
# No Zig dependency

[profile.dev]
panic = "abort"
opt-level = 2
overflow-checks = true

[profile.release]
panic = "abort"
lto = "fat"
opt-level = 3
codegen-units = 1
strip = "symbols"
overflow-checks = false

[package.metadata.bootimage]
default-target = "x86_64-astral.json"