[package]
name = "astral-kernel"
version = "0.3.0"
edition = "2021"
authors = ["Astral OS Team"]

[lib]
path = "src/lib.rs"

[[bin]]
name = "astral-kernel"
path = "src/main.rs"

[dependencies]
spin = { version = "0.9", default-features = false, features = ["spin_mutex"] }
limine = "0.5"
noto-sans-mono-bitmap = { version = "0.3.1", default-features = false, features = ["size_20", "regular" ,"unicode-basic-latin","unicode-latin-1-supplement"]}
bitflags = "2.4"

[build-dependencies]
# No Zig dependency

[profile.dev]
panic = "abort"
opt-level = 2
overflow-checks = true
debug=false

[profile.release]
panic = "abort"
lto = "fat"
opt-level = 3
codegen-units = 1
strip = false
overflow-checks = false

[package.metadata.bootimage]
default-target = "x86_64-astral.json"
